version: 0.2

phases:
  install:
    commands:
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
    - npm install --silent --no-progress
  build:
    commands:
    - mkdir -p target/stg
    - mkdir target/prod
    - serverless package --package target/stg --stage stg -v -r us-east-1
    - serverless package --package target/prod --stage prod -v -r us-east-1
  post_build:
    - serverless deploy prod -v

artifacts:
  files:
  - target/**/*
  - serverless.yml
  - deploy.sh