service: lmbda-pdf
provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  environment:
    STAGE: ${opt:stage}

plugins:
  - serverless-offline

custom:
  apigwBinary:
    types:
      - 'application/pdf'
  
package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  getpdf:
    handler: handler.getpdf
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /getPDF
          method: post
  
  getHTML:
    handler: handler.getHTML
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /getHTML
          method: post  

  getWord:
    handler: handler.getWord
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /getWord
          method: post

  getpreviewpdf:
    handler: handler.getpreviewpdf
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /getPreview
          method: post

  getCharacters:
    handler: shakespearedb.getCharacters
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /getCharacters
          method: get
          request:
            parameters: true

  getWorks:
    handler: shakespearedb.getWorks
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /getWorks
          method: get
          request:
            parameters: true

  getChapters:
    handler: shakespearedb.getChapters
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /getChapters
          method: get
          request:
            parameters: true

  getSections:
    handler: shakespearedb.getSections
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /getSections
          method: get
          request:
            parameters: true

  getParagraphs:
    handler: shakespearedb.getParagraphs
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /getParagraphs
          method: get
          request:
            parameters: true  
            
  getParagraphsRepeater:
    handler: shakespearedb.getParagraphsRepeater
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /getParagraphsRepeater
          method: get
          request:
            parameters: true
             
  getParagraphsRepeater2:
    handler: shakespearedb.getParagraphsRepeater2
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /getParagraphsRepeater2
          method: get
          request:
            parameters: true
            
  saveView:
    handler: shakespearedb.saveView
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /saveView
          method: post

  insertBreakDown:
    handler: breakdown.insertBreakDown
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /insertBreakDown
          method: post
  
  getBreakDowns:
    handler: breakdown.getBreakDowns
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /getBreakDowns
          method: get
          request:
            parameters: true  

resources: # CloudFormation template syntax from here on.
  Resources:
    breakdownsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: breakdownsTable
        AttributeDefinitions:
          - AttributeName: projectTitle
            AttributeType: S          
          - AttributeName: productionCompany
            AttributeType: S
        KeySchema:
          - AttributeName: projectTitle
            KeyType: HASH
          - AttributeName: "productionCompany"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
