service: lmbda-pdf
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    STAGE: ${opt:stage}

plugins:
  - serverless-offline

custom:
  apigwBinary:
    types:
      - 'application/pdf'
  
package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  getpdf:
    handler: handler.getpdf
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: /getPDF
          method: post
  
  getHTML:
    handler: handler.getHTML
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: /getHTML
          method: post  

  getWord:
    handler: handler.getWord
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: /getWord
          method: post

  getpreviewpdf:
    handler: handler.getpreviewpdf
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: /getPreview
          method: post

  getCharacters:
    handler: shakespearedb.getCharacters
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: /getCharacters
          method: get
          request:
            parameters: true

  getWorks:
    handler: shakespearedb.getWorks
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: /getWorks
          method: get

  getChapters:
    handler: shakespearedb.getChapters
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: /getChapters
          method: get
          request:
            parameters: true

  getSections:
    handler: shakespearedb.getSections
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: /getSections
          method: get
          request:
            parameters: true

  getParagraphs:
    handler: shakespearedb.getParagraphs
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: /getParagraphs
          method: get
          request:
            parameters: true